# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_password_plaintext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_plaintext',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
