# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20170725_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw_salt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
